### ISSUE TITLE
LICENSE.txt please

### ISSUE THREAD

**Issue by PaluMacil** [jorendorff/tinysearch#3]
I loved the talk! Thanks for making a fun and hilarious talk which was obviously rehearsed to perfection. I am going to go back through it a couple times, but I'd love to see a license specified in the repo. I prefer MIT, but even if it's a "use this for learning only" style license, I'd prefer it over none being specified before I clone it. :) Thanks again!

**Comment by jorendorff** [comment]
Thanks for the reminder! Done.
