### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ghost** [jorendorff/tinysearch#4]
dear jorendorff
i cant run this steps could you help me

 python tiny.py small-sample to create a search index!

pip install flask

FLASK_DEBUG=1 FLASK_APP=web.py flask run to start the web server!

**Comment by jorendorff** [comment]
I can't tell what didn't work here, but I have improved the readme to try and make the instructions clearer even if you're not a Python expert.

**Comment by ghost** [comment]
i did this, it was 1 year ago. But if it is possible i have another problem for now. I have client and server side  but they are not working with eachother but they are workinh seperatly i tried both of them is working but client cant do a request from server idk why can you help me if it possible ? thank you
https://github.com/caglaralpi/todolist

**Comment by jorendorff** [comment]
I'm sorry, that doesn't look like something I can help you with.
